name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Optional scheduled security scans
  # schedule:
  #   - cron: '0 5 * * 1'

jobs:
  # 1) Build everything (as you had)
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Initial with Maven
        working-directory: ./initial
        run: ./mvnw --batch-mode clean package

      - name: Build Initial with Gradle
        working-directory: ./initial
        run: ./gradlew build

      - name: Build Initial Kotlin with Gradle
        working-directory: ./initial-kotlin
        run: ./gradlew build

      - name: Build Complete with Maven
        working-directory: ./complete
        run: ./mvnw --batch-mode clean package

      - name: Build Complete with Gradle
        working-directory: ./complete
        run: ./gradlew build

      - name: Build Complete Kotlin with Gradle
        working-directory: ./complete-kotlin
        run: ./gradlew build

  # 2) CodeQL (Java extractor covers Java + Kotlin)
  codeql:
    name: CodeQL (Java/Kotlin)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: initial
            tool: maven
          - module: complete
            tool: maven
          - module: initial-kotlin
            tool: gradle
          - module: complete-kotlin
            tool: gradle
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: security-extended,security-and-quality

      # Build Maven modules
      - name: Build with Maven
        if: matrix.tool == 'maven'
        run: mvn -B -f "${{ matrix.module }}/pom.xml" -DskipTests package

      # Build Gradle modules
      - name: Build with Gradle
        if: matrix.tool == 'gradle'
        run: |
          if [ -x "./${{ matrix.module }}/gradlew" ]; then
            (cd "${{ matrix.module }}" && ./gradlew build -x test)
          else
            gradle -p "${{ matrix.module }}" build -x test
          fi

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

  sonarcloud:
    name: SonarCloud (repo-wide)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      # Build Java modules (Maven)
      - name: Build Java modules
        run: |
          mvn -B -f initial/pom.xml -DskipTests clean package
          mvn -B -f complete/pom.xml -DskipTests clean package

      # Build Kotlin modules (Gradle)
      - name: Build Kotlin modules
        run: |
          if [ -x "./initial-kotlin/gradlew" ]; then
            (cd initial-kotlin && ./gradlew build -x test)
          else
            gradle -p initial-kotlin build -x test
          fi
          if [ -x "./complete-kotlin/gradlew" ]; then
            (cd complete-kotlin && ./gradlew build -x test)
          else
            gradle -p complete-kotlin build -x test
          fi

      - name: SonarCloud Scan (single project)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=research-projects-all
            -Dsonar.projectKey=research-projects-all_gs-rest-service-main-tutorial-2
            -Dsonar.sources=initial/src/main,complete/src/main,initial-kotlin/src/main,complete-kotlin/src/main
            -Dsonar.tests=initial/src/test,complete/src/test,initial-kotlin/src/test,complete-kotlin/src/test
            -Dsonar.java.binaries=initial/target/classes,complete/target/classes,initial-kotlin/build/classes/java/main,initial-kotlin/build/classes/kotlin/main,complete-kotlin/build/classes/java/main,complete-kotlin/build/classes/kotlin/main
            -Dsonar.java.test.binaries=initial/target/test-classes,complete/target/test-classes,initial-kotlin/build/classes/java/test,initial-kotlin/build/classes/kotlin/test,complete-kotlin/build/classes/java/test,complete-kotlin/build/classes/kotlin/test


  
